name: Build desktop version

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  macOS_buld:
    name: building on macos
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, and test
        run: |
          yarn install
          yarn test
        env:
          CI: false
      - name: Build on MacOS
        env:
          ELECTRON: true
          # APP_VERSION_NUMBER: 0.5.9
        run: yarn build
      - name: Build Electron
        env:
          ELECTRON: true
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: yarn mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/storage-manager.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
